#!/bin/sh -ex

hpctesttool="$1"
hpcrun="$2"
tstexe_1loop="$3"

trap 'rm -rf "$tmpdir"' EXIT
tmpdir=$(mktemp --directory --tmpdir=.)

"$hpcrun" -o "$tmpdir"/m -e REALTIME@1000 "$tstexe_1loop"
"$hpctesttool" test produces-profiles -t4 "$tmpdir"/m
