#!/bin/sh -ex

hpctesttool="$1"
hpcrun="$2"
tstexe_1loop="$3"

trap 'rm -rf "$tmpdir"' EXIT
tmpdir=$(mktemp --directory --tmpdir=.)

if [ "$(cat /proc/sys/kernel/perf_event_paranoid)" -gt 1 ]; then exit 77; fi

"$hpcrun" -o "$tmpdir"/m --disable-auditor -e perf::cpu-clock@f100 -e perf::task-clock@1000000 "$tstexe_1loop"
"$hpctesttool" test produces-profiles -t4 "$tmpdir"/m
