// OMPT API functions

ompt_interface_fn(ompt_enumerate_state)
ompt_interface_fn(ompt_set_callback)
ompt_interface_fn(ompt_get_callback)
ompt_interface_fn(ompt_get_parallel_id)
ompt_interface_fn(ompt_get_state)
ompt_interface_fn(ompt_get_idle_frame)
ompt_interface_fn(ompt_get_task_id)
ompt_interface_fn(ompt_get_task_frame)
ompt_interface_fn(ompt_get_ompt_version)
ompt_interface_fn(ompt_get_runtime_version)
