#!/bin/sh -ex

hpctesttool="$1"
hpcrun="$2"
tstexe_sycl_vecadd="$3"
event="$4"
trace="$5"

case "$trace" in
"")
  threads=4
  tracearg=--no-trace
  ;;
-t|-tt)
  threads=4
  tracearg=--trace
  ;;
*)
  exit 2
  ;;
esac

trap 'rm -rf "$tmpdir"' EXIT
tmpdir=$(mktemp --directory --tmpdir=.)

# shellcheck disable=SC2086
"$hpcrun" -o "$tmpdir"/m -e "$event" $trace "$tstexe_sycl_vecadd"
"$hpctesttool" test produces-profiles -t "$threads" "$tracearg" "$tmpdir"/m
