#!/bin/sh
#
#  SymtabAPI configure.
#
#  $Id$
#

PKG_NAME=symtabAPI
work=symtabAPI/src/dyninst

config=make.config
config_orig="${config}.orig"

. ../build-utils/configure.inc
pre_configure
prefix="$symtabAPI_prefix"

cd "$work" || die "unable to cd: $work"

# Configure doesn't substitute CC, CXX and flags, so we sed-edit
# make.config instead.

test -f "$config_orig" || mv -f "$config" "$config_orig"
test -f "$config_orig" || die "missing config file: $config"
rm -f "$config"

cat "$config_orig" |
    sed \
	-e "s,^HPC_CC .*\$,HPC_CC = $CC," \
	-e "s,^HPC_CXX .*\$,HPC_CXX = $CXX," \
	-e "s,^HPC_CFLAGS .*\$,HPC_CFLAGS = $CFLAGS," \
	-e "s,^HPC_CXXFLAGS .*\$,HPC_CXXFLAGS = $CXXFLAGS," \
	> "$config"

test $? -eq 0 || die "configure failed"

set -- \
    CC="$CC"  CFLAGS="$CFLAGS" \
    CXX="$CXX"  CXXFLAGS="$CXXFLAGS" \
    --prefix="$prefix" \
    --bindir="${prefix}/bin" \
    --includedir="${prefix}/include" \
    --libdir="${prefix}/lib" \
    --with-libdwarf-incdir="$libdwarf_inc" \
    --with-libdwarf-libdir="$libdwarf_lib" \
    --with-libelf-incdir="$libelf_inc" \
    --with-libelf-libdir="$libelf_lib" \
    --with-libunwind-incdir="$libunwind_inc" \
    --with-libunwind-libdir="$libunwind_lib" \
    --with-libxml2-incdir="$libxml2_inc" \
    --with-libxml2-libdir="$libxml2_lib" \
    --with-libiberty-libdir="${binutils_prefix}/lib64" \
    "$@"

if test -n "$is_cross_compile" ; then
    set -- --host="$host" "$@"
fi

echo ./configure "$@"
./configure "$@"
test $? -eq 0 || die "configure failed"

post_configure
