#
#  Binutils Makefile.
#
#  $Id$
#

PKG_NAME = binutils
SRC_DIR = version-binutils-2.20.1

FETCH_TARFILE = binutils-2.20.1-hpc-r117.tar.gz

BUILD_CMD   = ./build
INSTALL_CMD = ./install

include ../build-utils/Makefile.inc
