# SPDX-FileCopyrightText: 2023-2024 Rice University
# SPDX-FileCopyrightText: 2024 Contributors to the HPCToolkit Project
#
# SPDX-License-Identifier: BSD-3-Clause

image:
  context: .devcontainer/
  file: .devcontainer/Dockerfile

vscode:
  extensions:
  - mesonbuild.mesonbuild

tasks:
- init: pipx ensurepath
