#!/bin/sh
# -*-Mode: sh;-*-

# $Id$

## **************************************************************************
##
## File: 
##    Regenerate 'configure' and 'Makefile.ins'
##
## Author:
##    Written by Nathan Tallent, Rice University.
##    
## **************************************************************************

#OPT="-Wall"
OPT=""

aclocal
libtoolize -f -c
automake -a -f -c ${OPT}
aclocal && autoconf ${OPT} && automake ${OPT}

#############################################################################
