#!/usr/bin/env python3

import click
from hpctoolkit.test.execution import hpcrun


@click.command()
def test_list_metrics():
    """Test that hpcrun can list the metrics it supports without error."""
    hpcrun("-L", cmd=[])


if __name__ == "__main__":
    test_list_metrics()  # pylint: disable=no-value-for-parameter)
