#define FIND (1 << 0)
#define INTV  (1 << 1)
#define ITIMER_HANDLER (1 << 2)
#define UNW (1 << 3)
#define SPLAY (1 << 4)
#define INTV2 (1 << 5)
#define TROLL (1 << 6)
#define UNW_INIT (1 << 7)
#define BASIC_INIT (1 << 8)
#define SAMPLE     (1 << 9)
#define SWIZZLE    (1 << 10)
#define FINALIZE   (1 << 11)
#define DATA_WRITE (1 << 12)
#define PAPI       (1 << 13)
#define DBG        (1 << 14)

#define NONE (0)
#define ALL (~0)
