# Dockerfile for CI image for Fedora 37

FROM registry.fedoraproject.org/fedora:37
ARG TARGETARCH

# Install all the packages required:
#  - Base system pieces required by Spack
#  - Compilers
#  - Extra utilities
# python3-boto3 is needed for S3 access
RUN yum update -y \
  && yum install -y \
    bzip2 \
    ccache \
    clang \
    eatmydata \
    file \
    gcc gcc-c++ gcc-gfortran \
    git \
    git-lfs \
    make \
    mercurial \
    patch \
    patchelf \
    perl-open \
    perl-FindBin \
    python3 \
    python3-boto3 \
    python3-pip \
    subversion \
    unzip \
    xz \
    zstd \
  && yum clean all && rm -rf /var/yum/* /var/dnf/* \
  && python3 -m pip --no-cache-dir install clingo

# Install the permanent Spack configuration
COPY config.yaml /etc/spack/

INCLUDE ../spack.inc
