#!/bin/sh
# -*-Mode: sh;-*-

# $Id$

## **************************************************************************
##
## File: 
##    Regenerate 'configure' and 'Makefile.ins'
##
## Author:
##    Written by Nathan Tallent, Rice University.
##    
## **************************************************************************

autoreconf --force --install --verbose


#-------------------------------------------------
# Redefine PACKAGE_STRING (see comments in ./configure)
#-------------------------------------------------

configure_fnm="./configure"
if test -f "${configure_fnm}" ; then
  sed -i -e "s/PACKAGE_STRING='hpctoolkit /PACKAGE_STRING='hpctoolkit-/" \
    ${configure_fnm}
else
  echo "*** Warning: cannot find ${configure_fnm} ***"
fi

#############################################################################
