#!/bin/sh
#
# Wrapper to run libmonitor with LD_PRELOAD.
#
# $Id$
#

die() {
    echo "Error: $@" 1>&2
    exit 1
}

if test "x$0" = x ; then
    die "Usage: $0 command arg ..."
fi

LIBMONITOR_SO="`dirname $0`/../lib/libmonitor.so"

if test ! -f "$LIBMONITOR_SO" ; then
    die "unable to find libmonitor.so"
fi

LD_PRELOAD="${LIBMONITOR_SO}:${LD_PRELOAD}"
export LD_PRELOAD
MONITOR_DEBUG=1
export MONITOR_DEBUG

exec "$@"
