#!/usr/bin/env python3

import argparse
import shutil
import tarfile
import tempfile
from pathlib import Path

parser = argparse.ArgumentParser(
    description="Open an xz-tarball generated by run.py and extract it to a directory"
)
parser.add_argument("input", type=Path)
parser.add_argument("output", type=Path)
args = parser.parse_args()
del parser

outdir = args.output.resolve(strict=False)
if outdir.exists():
    if outdir.is_dir():
        shutil.rmtree(outdir)
    else:
        outdir.unlink()
with tempfile.TemporaryDirectory(
    dir=outdir.parent, prefix="." + outdir.name + ".tmp.", ignore_cleanup_errors=True
) as tmpdir:
    tmpdir = Path(tmpdir)
    with tarfile.open(args.input, "r:*") as tarf:
        tarf.extractall(tmpdir)
    if not any(x.suffix == ".hpcrun" for x in tmpdir.iterdir()):
        raise ValueError("No .hpcrun files found in tarball!")
    tmpdir.replace(outdir)

outdir.touch()
