#!/bin/sh -ex

hpctesttool="$1"
hpcrun="$2"
hpcstruct="$3"
min_samples="$4"
output="$5"
shift 5  # Remaining arguments go to hpcrun

trap 'rm -rf "$tmpdir"' EXIT
tmpdir=$(mktemp --directory --tmpdir=.)

for _attempt in 1 2 3 4 5 6 7 8 9 10; do
  "$hpcrun" -o "$tmpdir"/m "$@"
  samples=$(
    grep -E 'SUMMARY:[[:space:]]+samples:[[:space:]]+[[:digit:]]+[[:space:]]+\(recorded:[[:space:]]+[[:digit:]]+' "$tmpdir"/m/*.log \
    | grep -Eo 'recorded:[[:space:]]+[[:digit:]]+' \
    | grep -Eo -m1 '[[:digit:]]+')
  if [ "$samples" -lt "$min_samples" ]; then continue; fi

  "$hpcstruct" --gpucfg=yes --nocache "$tmpdir"/m
  "$hpctesttool" test tarball "$tmpdir"/m "$output"
  exit 0
done
