#! /usr/bin/env python

from sys import argv
import os
argv = [ a.endswith('f90main.o') and 'Static/f90main.o' or a for a in argv]

argv[0] = 'ld'

print "static collect2 called with:","|",argv,"|"

os.environ['PATH'] = ':'.join(os.environ['PATH'].split(':')[1:])
os.execvp('collect2',argv)

#plist = os.environ['PATH'].split(':')[1:]
#print "os plist = ",':'.join(plist)
#print "os path = ",os.environ['PATH']


