#! /bin/bash
#
# -*- Mode:Shell-script -*-
#

#
# compute path of hpcrun
#

pth=$(dirname $(dirname $(which hpcrun)))/lib/hpctoolkit

LD_LIBRARY_PATH=$pth${LD_LIBRARY_PATH:+:}$LD_LIBRARY_PATH exec hpcrun -e SYNC@3 "$@"
