#!/usr/bin/env python3

import click
from hpctoolkit.test.execution import hpcrun


@click.command()
@click.option("-p", "--procs", type=int, default=1, help="Expected number of processes")
@click.option(
    "-t", "--threads-per-proc", type=int, default=1, help="Expected number of threads per process"
)
@click.option("--trace", is_flag=True, help="Enable tracing (hpcrun -t)")
@click.argument("cmd", nargs=-1, required=True)
def test_produces_profiles(procs: int, threads_per_proc: int, trace: bool, cmd: tuple[str]):
    """Test that measuring CMD with ROCm support produces an expected number of profiles."""
    with hpcrun("-e", "gpu=amd", ("-t" if trace else None), cmd=cmd) as meas:
        meas.check_standard(
            procs=procs, threads_per_proc=threads_per_proc + (1 if trace else 0), traces=trace
        )


if __name__ == "__main__":
    test_produces_profiles()  # pylint: disable=no-value-for-parameter)
