#! /bin/bash

#ln -s src/core/symtabAPI/h ./include
#ln -s src/x86_64-unknown-linux2.4
#pushd src/x86_64-unknown-linux2.4/lib && ln -s libelf.so.0 libelf.so && popd
export PLATFORM=x86_64-unknown-linux2.4
export DYNINST_ROOT=`pwd`
pushd src/core && make && popd
