#!/bin/sh -ex

hpctesttool="$1"
hpcprof="$2"
meas="$3"
output="$4"
yaml_output="$5"

trap 'rm -rf "$tmpdir"' EXIT
tmpdir=$(mktemp --directory --tmpdir=.)

"$hpctesttool" test untarball "$meas" "$tmpdir"/m
"$hpcprof" -j4 --foreign "$tmpdir"/m -o "$tmpdir"/d
"$hpctesttool" test tarball "$tmpdir"/d "$output"
if [ "$yaml_output" ]; then
  "$hpctesttool" test yaml "$tmpdir"/d "$yaml_output"
fi
