#!/bin/sh

# $Id$

# A sample SH script for collecting profile data using uprofile on an
# EV67-based machine.
#
# Usage notes:
#   - Assign the application name to HPCAPPL (here or in the environment).
#     Similarly, assign program arguments to HPCARGS.
#   - 'hpcview_cfg-alpha.xml' is the corresponding hpcview configuration
#     file.
#
# This works for a single process applications only.

#############################################################################

#HPCPATH="The path to the application"
#HPCAPPL="The application name"
#HPCARGS="Arguments to the application"

# Replace me or define in calling environment
HPCPATH="."
#HPCAPPL="hydro.alpha-OSF1.f77-O3"
#HPCARGS=""

if [ -z "${HPCAPPL}" ] ; then
  echo "Please set HPCAPPL"
  exit 1
fi

HPCRUN="${HPCPATH}/${HPCAPPL} ${HPCARGS}"

#############################################################################

# The first three metrics are collected using the hardware performance
# counters.

uprofile cycles0 ${HPCRUN}
prof -lines ${HPCPATH}/${HPCAPPL} umon.out > ${HPCAPPL}.cycles
ptran <${HPCAPPL}.cycles >cycles.pxml

uprofile replay ${HPCRUN}
prof -lines ${HPCPATH}/${HPCAPPL} umon.out > ${HPCAPPL}.replay
ptran <${HPCAPPL}.replay >replay.pxml

uprofile bcachemisses ${HPCRUN}
prof -lines ${HPCPATH}/${HPCAPPL} umon.out > ${HPCAPPL}.bcachemisses
ptran <${HPCAPPL}.bcachemisses >bcachemisses.pxml


# The following lines collect information on events measured by
# ProfileMe on EV67 and later processors

uprofile delay ${HPCRUN}
prof -lines ${HPCPATH}/${HPCAPPL} umon.out > ${HPCAPPL}.delay
ptran <${HPCAPPL}.delay >delay.pxml

uprofile inflt_retires ${HPCRUN}
prof -lines ${HPCPATH}/${HPCAPPL} umon.out > ${HPCAPPL}.inflt_retires
ptran <${HPCAPPL}.inflt_retires >inflt_retires.pxml

uprofile inflt_bcache ${HPCRUN}
prof -lines ${HPCPATH}/${HPCAPPL} umon.out > ${HPCAPPL}.inflt_bcache
ptran <${HPCAPPL}.inflt_bcache >inflt_bcache.pxml

uprofile inflt_replays ${HPCRUN}
prof -lines ${HPCPATH}/${HPCAPPL} umon.out > ${HPCAPPL}.inflt_replays
ptran <${HPCAPPL}.inflt_replays >inflt_replays.pxml

uprofile cycles_per_ret ${HPCRUN}
prof -lines ${HPCPATH}/${HPCAPPL} umon.out > ${HPCAPPL}.cycles_per_ret
ptran <${HPCAPPL}.cycles_per_ret >cycles_per_ret.pxml

