#!/usr/bin/env python3

# SPDX-FileCopyrightText: 2022-2024 Rice University
#
# SPDX-License-Identifier: BSD-3-Clause

# pylint: disable=invalid-name,missing-module-docstring

import os
import random
import sys

if len(sys.argv) <= 1:
    print("Usage: thread-disruptive.py <command>...")
    sys.exit(2)

# Adjust the processor affinity, if we have access to that.
threads = 1
if hasattr(os, "sched_getaffinity") and hasattr(os, "sched_setaffinity"):
    os.sched_setaffinity(0, random.sample(list(os.sched_getaffinity(0)), threads))

# Exec to the subservient command
os.execvp(sys.argv[1], sys.argv[1:])
