#!/usr/bin/env python3

import os
import stat
import sys

py = sys.argv[1]
with open(sys.argv[2], encoding="utf-8") as in_f, open(sys.argv[3], "w", encoding="utf-8") as out_f:
    shebang = in_f.readline()
    if shebang.strip() != "#!/usr/bin/env python3":
        raise ValueError(f"Script does not have a python3 shebang: {sys.argv[2]}")

    out_f.write(f"#!{py}\n")
    for line in in_f:
        out_f.write(line)

os.chmod(sys.argv[3], stat.S_IMODE(os.stat(sys.argv[2]).st_mode))
