#!/bin/sh -ex

hpctesttool="$1"
hpcrun="$2"
hpcprof="$3"
python="$4"
script="$5"
threads="$6"

trap 'rm -rf "$tmpdir"' EXIT
tmpdir=$(mktemp --directory --tmpdir=.)

"$hpcrun" -o "$tmpdir"/m -a python -e REALTIME --disable-auditor "$python" "$script"
"$hpctesttool" test produces-profiles -t "$threads" "$tmpdir"/m
"$hpcprof" -j1 -o "$tmpdir"/d "$tmpdir/m"
"$hpctesttool" test unwind-py-simple "$script" "$tmpdir"/d
