#!/bin/sh
# Testing: set -x: line by line (set -n: syntax)
# set -x

# $Id$

## **************************************************************************
##
## Launching script
##
## John Mellor-Crummey and Nathan Tallent
##
## **************************************************************************

#############################################################################
# Find where we were called from
#############################################################################

# Note: HPCTOOLKIT must be absolute.  We could have autoconf/automake
# insert the installation dir and the platform

BINDIR=`dirname $0`

if [ ${BINDIR} = '.' ]; then 
    ROOTDIR_REL='..';
else
    ROOTDIR_REL=`dirname ${BINDIR}`;
fi

ROOTDIR=`cd ${ROOTDIR_REL} && pwd`

HPCTOOLKIT=${ROOTDIR}
BINARY="$0-bin" # ${HPCTOOLKIT}/bin/ `basename $0` bin

unset BINDIR
unset ROOTDIR
unset ROOTDIR_REL

#echo "--> $0"
#echo "--> ${HPCTOOLKIT}"
#echo "--> ${BINARY}"

#############################################################################
# Set environment for process
#############################################################################

export HPCTOOLKIT

#HPCTOOLKIT_PLATFORM=`cd ${HPCTOOLKIT}/libexec/hpctoolkit && ./hpcplatform`
#export HPCTOOLKIT_PLATFORM

XERCESC_PATH="${HPCTOOLKIT}/lib/hpctoolkit/xercesc"

if test -z "${LD_LIBRARY_PATH}" ; then
  LD_LIBRARY_PATH=${XERCESC_PATH}
else
  LD_LIBRARY_PATH=${XERCESC_PATH}:${LD_LIBRARY_PATH}
fi
export LD_LIBRARY_PATH

unset XERCESC_PATH

#############################################################################
# exec binary image
#############################################################################

if [ -r "${BINARY}" -a -x "${BINARY}" ]; then
    if [ $# -eq 0 ]; then
	exec ${BINARY}
    else
	exec ${BINARY} "$@"
    fi
else
    echo "$0 fatal error: cannot exec '${BINARY}'"
    exit 1;
fi
