#!/bin/bash -ex

# SPDX-FileCopyrightText: 2023-2024 Rice University
# SPDX-FileCopyrightText: 2024 Contributors to the HPCToolkit Project
#
# SPDX-License-Identifier: BSD-3-Clause

hpctesttool="$1"
hpcrun="$2"
tstexe_amd_vecadd="$3"
trace="$4"
shift 4
remaining_args=("$@")

set -- '^NODE [^A-Z]+\s+(((CORE [^A-Z]+\s+)?THREAD [^A-Z]+)|(GPUCONTEXT [^A-Z]+\s+GPUSTREAM [^A-Z]+))$' \
  'THREAD 0/0:logical' \
  'GPUCONTEXT [0-9a-f]+/[0-9a-f]+:logical GPUSTREAM [0-9a-f]+/[0-9a-f]+:logical'

case "$trace" in
"")
  # When not tracing, we don't expect a GPU profile because performance is attributed in the CPU profile
  set -- '^NODE [^A-Z]+\s+(CORE [^A-Z]+\s+)?THREAD [^A-Z]+$' \
    'THREAD 0/0:logical'
  tracearg=--no-trace
  ;;
-t|-tt)
  tracearg=--trace
  ;;
*)
  exit 2
  ;;
esac

trap 'rm -rf "$tmpdir"' EXIT
tmpdir=$(mktemp --directory --tmpdir=.)

# shellcheck disable=SC2086
"$hpcrun" -o "$tmpdir"/m -e gpu=amd $trace "${remaining_args[@]}" "$tstexe_amd_vecadd"
"$hpctesttool" test produces-profiles "$tracearg" "$tmpdir"/m "$@"
