#!/bin/sh
# -*-Mode: sh;-*-

# $Id$

## **************************************************************************
##
## File: 
##    Regenerate 'configure' and 'Makefile.ins'
##
## Author:
##    Written by Nathan Tallent, Rice University.
##    
## **************************************************************************

aclocal
libtoolize -f -c
automake -a -f -c
aclocal && autoconf && automake

#############################################################################
