#!/usr/bin/env python3

import sys
import xml.sax
import click

from hpctoolkit.test.execution import hpcstruct

@click.command()
@click.argument("binary", type=click.Path(exists=True, readable=True, dir_okay=False))
def test_runs(binary):
    """Test that the given BINARY can be analyzed without crashing (or error return code)."""
    with hpcstruct(binary) as structfile:
        xml.sax.parse(structfile, xml.sax.handler.ContentHandler())
