#!/bin/sh -e

# SPDX-FileCopyrightText: 2023-2024 Rice University
# SPDX-FileCopyrightText: 2024 Contributors to the HPCToolkit Project
#
# SPDX-License-Identifier: BSD-3-Clause

hpcprof="$1"
meas_stamp="$2"
output_stamp="$3"
shift 3  # Remaining arguments are passed to hpcprof

meas="$(dirname "$meas_stamp")/$(basename "$meas_stamp" .fresh)"
output="$(dirname "$output_stamp")/$(basename "$output_stamp" .fresh)"

# Produce the database
rm -rf "$output"
"$hpcprof" -j4 "$@" "$meas" -o "$output"

# Clean up all non-essential files
rm \
  "$output"/FORMATS.md \
  "$output"/metrics/METRICS.yaml.ex \
  # END

# Create/update the stampfile
date > "$output_stamp"
