#!/bin/sh -ex

# SPDX-FileCopyrightText: 2023-2024 Rice University
#
# SPDX-License-Identifier: BSD-3-Clause

hpctesttool="$1"
hpcrun="$2"
tstexe_cuda_vecadd="$3"
event="$4"
trace="$5"

set -- '^NODE [^A-Z]+\s+(((CORE [^A-Z]+\s+)?THREAD [^A-Z]+)|(GPUCONTEXT [^A-Z]+\s+GPUSTREAM [^A-Z]+))$' \
  'THREAD 0/0:logical' \
  'GPUCONTEXT [0-9a-f]+/[0-9a-f]+:logical GPUSTREAM [0-9a-f]+/[0-9a-f]+:logical'

case "$trace" in
"")
  # When not tracing, we don't expect a GPU profile because performance is attributed in the CPU profile
  set -- '^NODE [^A-Z]+\s+(CORE [^A-Z]+\s+)?THREAD [^A-Z]+$' \
    'THREAD 0/0:logical'
  tracearg=--no-trace
  ;;
-t|-tt)
  tracearg=--trace
  ;;
*)
  exit 2
  ;;
esac

trap 'rm -rf "$tmpdir"' EXIT
tmpdir=$(mktemp --directory --tmpdir=.)

# shellcheck disable=SC2086
"$hpcrun" -o "$tmpdir"/m -e "$event" -ck HPCRUN_CUPTI_SYSTEM_ERROR_EXITCODE=77 $trace "$tstexe_cuda_vecadd"
"$hpctesttool" test produces-profiles "$tracearg" "$tmpdir"/m "$@"
