#!/bin/sh
#
#  Old Monitor install.
#
#  These file names conflict with SciDAC libmonitor, so we put them in
#  a separate directory.
#
#  $Id$
#

PKG_NAME=old-monitor
temp=monitor-080825/temp-install

. ../build-utils/configure.inc
pre_install
prefix="$old_monitor_prefix"

mkdir -p "$prefix" || die "unable to mkdir: $prefix"

cd "$temp" || die "unable to cd: $temp"

tar cf - include lib* | ( cd "$prefix" && tar xvf - )
test $? -eq 0 || die "install failed"

post_install
