#!/usr/bin/env python3

import click
from hpctoolkit.test.execution import hpcrun


@click.command()
@click.option("-p", "--procs", type=int, default=1, help="Expected number of processes")
@click.option(
    "-t", "--threads-per-proc", type=int, default=1, help="Expected number of threads per process"
)
@click.argument("cmd", nargs=-1, required=True)
def test_produces_profiles(procs: int, threads_per_proc: int, cmd: tuple[str]):
    """Test that measuring CMD produces an expected number of profiles."""
    with hpcrun(cmd=cmd) as meas:
        meas.check_standard(procs=procs, threads_per_proc=threads_per_proc)


if __name__ == "__main__":
    test_produces_profiles()  # pylint: disable=no-value-for-parameter
