#!/bin/sh -ex

# SPDX-FileCopyrightText: 2023-2024 Rice University
# SPDX-FileCopyrightText: 2024 Contributors to the HPCToolkit Project
#
# SPDX-License-Identifier: BSD-3-Clause

hpctesttool="$1"
hpcrun="$2"
tstexe_1loop="$3"

trap 'rm -rf "$tmpdir"' EXIT
tmpdir=$(mktemp --directory --tmpdir=.)

"$hpcrun" -o "$tmpdir"/m -e CPUTIME@500 "$tstexe_1loop"
# "$hpctesttool" test produces-profiles -t4 "$tmpdir"/m
"$hpctesttool" test produces-profiles "$tmpdir"/m \
  '^NODE [^A-Z]+\s+(CORE [^A-Z]+\s+)?THREAD 0/0:logical$'
