#!/bin/bash

# Find an image that is compatible with the current packaging step
# Outputs the appropriate image prefix to reuse, or to generate (and returns an error exit code)
# Usage: find-reusable-img <image>:<arch>...

gen_cksum="$(realpath "$(dirname "$0")")"/gen-cksum

# Helper functions
reskopeo() {
  skopeo "$@" && return 0
  for _ in 2 3; do
    echo "Skopeo failed, retrying after 3 seconds..." >&2
    sleep 3
    skopeo "$@" && return 0
  done
  return 1
}
fetch_cksum() {
  reskopeo inspect --no-tags --format '{{index .Labels "edu.rice.hpctoolkit.ci.spec"}}' docker://"$1"
}

try_prefix() {
  for imgspec in "$@"; do
    image="$(echo "$imgspec" | cut -d: -f1)" || exit $?
    arch="$(echo "$imgspec" | cut -d: -f2)" || exit $?
    echo "Attempting to validate image $prefix-$image-$arch..." >&2
    expected_cksum="$("$gen_cksum" "$imgspec")" || exit $?
    got_cksum="$(fetch_cksum "$prefix-$image-$arch")" || exit $?
    if [ "$expected_cksum" != "$got_cksum" ]; then
      return 1
    fi
  done
}

# 1. Reuse from the default branch first. This will likely be the most up-to-date image available.
prefix="$CI_REGISTRY_IMAGE/ci:latest-$CI_DEFAULT_BRANCH"
if try_prefix "$@"; then
  echo "$prefix"
  exit 0
fi

# 2. Reuse from our MR target branch next, if we have one and it's protected
if [ "$CI_MERGE_REQUEST_TARGET_BRANCH_PROTECTED" = true ] && [ "$CI_MERGE_REQUEST_TARGET_BRANCH_NAME" != "$CI_DEFAULT_BRANCH" ]; then
  prefix="$CI_REGISTRY_IMAGE/ci:latest-$CI_MERGE_REQUEST_TARGET_BRANCH_NAME"
  if try_prefix "$@"; then
    echo "$prefix"
    exit 0
  fi
fi

# 3. Reuse from a prior pipeline on this branch/MR
if [ "$CI_COMMIT_REF_PROTECTED" = true ]; then
  depprefix='latest-'
else
  depprefix='nonprot-'
fi
prefix="$CI_REGISTRY_IMAGE/ci:$depprefix$CI_COMMIT_REF_SLUG"
if try_prefix "$@"; then
  echo "$prefix"
  exit 0
fi

# Failed to find a suitable image, abort
exit 1
