#!/bin/sh

# $Id$
## * BeginRiceCopyright *****************************************************
##
## Copyright ((c)) 2002, Rice University
## All rights reserved.
##
## Redistribution and use in source and binary forms, with or without
## modification, are permitted provided that the following conditions are
## met:
##
## * Redistributions of source code must retain the above copyright
##   notice, this list of conditions and the following disclaimer.
##
## * Redistributions in binary form must reproduce the above copyright
##   notice, this list of conditions and the following disclaimer in the
##   documentation and/or other materials provided with the distribution.
##
## * Neither the name of Rice University (RICE) nor the names of its
##   contributors may be used to endorse or promote products derived from
##   this software without specific prior written permission.
##
## This software is provided by RICE and contributors "as is" and any
## express or implied warranties, including, but not limited to, the
## implied warranties of merchantability and fitness for a particular
## purpose are disclaimed. In no event shall RICE or contributors be
## liable for any direct, indirect, incidental, special, exemplary, or
## consequential damages (including, but not limited to, procurement of
## substitute goods or services; loss of use, data, or profits; or
## business interruption) however caused and on any theory of liability,
## whether in contract, strict liability, or tort (including negligence
## or otherwise) arising in any way out of the use of this software, even
## if advised of the possibility of such damage.
##
## ******************************************************* EndRiceCopyright *

###############################################################################
#
#  File:
#     hFinishGNUBinutilsInstall
#
#  Purpose:
#     Copies extra files for HPCTools that GNU binutil's 'make install'
#     leaves behind.  
#
#  Arguments:
#     none
#
#  Description:
#
#  History:
#
###############################################################################

###############################################################################
#
# This script assumes that it is run after GNU binutils has been made and
# installed via 'make install'.  Because of this, we first check for the
# existence of $HPCTOOLKIT_BINUTILS_INSTALL, which should come from the 
# environment.
#
# The script also assumes that it is run in the same directory that
# binutils has been made.
#
###############################################################################

if [ -z "${HPCTOOLKIT_PLATFORM}" ]; then
    echo "Error: HPCTOOLKIT_PLATFORM is undefined."
    exit 1
fi

if [ -z "${HPCTOOLKIT_BINUTILS_INSTALL}" ]; then
    echo "Error: HPCTOOLKIT_BINUTILS_INSTALL is undefined."
    exit 1
fi

if [ ! -d "${HPCTOOLKIT_BINUTILS_INSTALL}" ]; then
    echo "Error: ${HPCTOOLKIT_BINUTILS_INSTALL} does not exist."
    exit 1
fi

############################################################
# 1. Copy extra libraries
############################################################

echo "Copying intl/libintl.a..."
cp intl/libintl.a ${HPCTOOLKIT_BINUTILS_INSTALL}/lib/.

############################################################
# 2. Copy extra headers
############################################################

echo "Copying include/demangle.h..."
cp include/demangle.h ${HPCTOOLKIT_BINUTILS_INSTALL}/include/.

############################################################
# 3. Library tweaking.
#    - To avoid symbol conflicts with the Sparc system demangler,
#      redefine GNU's 'cplus_demangle' to 'gnu_cplus_demangle'.
#      HPCTools is compiled with the latter as the prototype.
#      (cf. HPCTools/src/include/gnu_demangle.h)
############################################################

if [ "x${HPCTOOLKIT_PLATFORM}" = "xsparc-SunOS" ]; then
    # Currently, even when binutils is built with shared libraries,
    # libiberty.a is static.  If it ever becomes dynamic, tweak
    # the binaries that might use it.
    echo "Tweaking libs (cplus_demangle --> gnu_cplus_demangle)..."

    objcopy="${HPCTOOLKIT_BINUTILS_INSTALL}/bin/objcopy"
    ocargs="--redefine-sym cplus_demangle=gnu_cplus_demangle"
    ${objcopy} ${ocargs} ${HPCTOOLKIT_BINUTILS_INSTALL}/lib/libiberty.a
else
    echo "Tweaking libs... (Skipping)".
fi

exit 0
