#!/bin/sh
# Testing: -n: syntax; -x: line by line
# set -x
# set -n

# $Id$
## * BeginRiceCopyright *****************************************************
##
## Copyright ((c)) 2002, Rice University
## All rights reserved.
##
## Redistribution and use in source and binary forms, with or without
## modification, are permitted provided that the following conditions are
## met:
##
## * Redistributions of source code must retain the above copyright
##   notice, this list of conditions and the following disclaimer.
##
## * Redistributions in binary form must reproduce the above copyright
##   notice, this list of conditions and the following disclaimer in the
##   documentation and/or other materials provided with the distribution.
##
## * Neither the name of Rice University (RICE) nor the names of its
##   contributors may be used to endorse or promote products derived from
##   this software without specific prior written permission.
##
## This software is provided by RICE and contributors "as is" and any
## express or implied warranties, including, but not limited to, the
## implied warranties of merchantability and fitness for a particular
## purpose are disclaimed. In no event shall RICE or contributors be
## liable for any direct, indirect, incidental, special, exemplary, or
## consequential damages (including, but not limited to, procurement of
## substitute goods or services; loss of use, data, or profits; or
## business interruption) however caused and on any theory of liability,
## whether in contract, strict liability, or tort (including negligence
## or otherwise) arising in any way out of the use of this software, even
## if advised of the possibility of such damage.
##
## ******************************************************* EndRiceCopyright *

###############################################################################
#
#  File:
#     hFinishCVSCheckout
#
#  Purpose:
#
#  Arguments:
#     none
#
#  Description:
#
#  History:
#
###############################################################################

###############################################################################
#
# This script assumes that it is run after GNU binutils has been made and
# installed via 'make install'.  Because of this, we first check for the
# existence of $HPCTOOLKIT_BINUTILS_INSTALL, which should come from the 
# environment.
#
# The script also assumes that it is run in the same directory that
# binutils has been made.
#
###############################################################################

if [ -z "${HPCTOOLKIT}" ] ; then
  echo "You must set your HPCTOOLKIT environment variable before sourcing"
  echo "this file."
  exit 1
fi

############################################################
# 1. Setup links for xerces libs
############################################################

xercesbase="${HPCTOOLKIT}/lib/xerces-c2_1_0"

xercesdirs="${xercesbase}/alpha-OSF1 ${xercesbase}/i686-Linux ${xercesbase}/ia64-Linux-ecpc ${xercesbase}/ia64-Linux-g++ ${xercesbase}/mips-IRIX64 ${xercesbase}/sparc-SunOS"

for dir in ${xercesdirs}; do
  if [ -d "${dir}" ] ; then
    #printf "${dir}\n"
    
    if [ ! -r "${dir}/libxerces-c.so.21" ] ; then
      ln -s "${dir}/libxerces-c.so.21.0" "${dir}/libxerces-c.so.21"
    fi
    if [ ! -r "${dir}/libxerces-c.so" ] ; then
      ln -s "${dir}/libxerces-c.so.21" "${dir}/libxerces-c.so"
    fi

  fi
done

if [ ! -d "${xercesbase}/ia64-Linux" ] ; then
  ln -s "${xercesbase}/ia64-Linux-g++" "${xercesbase}/ia64-Linux"
fi


############################################################
# 2. Conditionally add links for building
############################################################

#ln -s /net/basuri4/eraxxon/HPCToolkit/obj/sparc ${HPCTOOLKIT_PLATFORM}

############################################################
# 4. Done
############################################################

exit 0

