#!/bin/sh -ex

# SPDX-FileCopyrightText: 2023-2024 Rice University
# SPDX-FileCopyrightText: 2024 Contributors to the HPCToolkit Project
#
# SPDX-License-Identifier: BSD-3-Clause

hpctesttool="$1"
hpcstruct="$2"
binary="$3"
shift 3  # Remaining arguments go to the hpctesttool

trap 'rm -rf "$tmpdir"' EXIT
tmpdir=$(mktemp --directory --tmpdir=.)

"$hpcstruct" -o "$tmpdir"/s.hpcstruct "$binary"
"$hpctesttool" test match-struct "$tmpdir"/s.hpcstruct "$binary" "$@"
