#!/bin/sh
# -*-Mode: sh;-*-

# $Id: autogen 828 2007-05-25 13:58:54Z eraxxon $

## **************************************************************************
##
## File: 
##    Regenerate 'configure' and 'Makefile.ins'
##
## Author:
##    Written by Nathan Tallent, Rice University.
##    
## **************************************************************************

autoreconf --force --install --verbose

#############################################################################
