#!/bin/sh

# SPDX-FileCopyrightText: 2023-2024 Rice University
# SPDX-FileCopyrightText: 2024 Contributors to the HPCToolkit Project
#
# SPDX-License-Identifier: BSD-3-Clause

venv="$1"
srcdir="$2"
output="$3"

do_pip() {
  "$venv"/bin/python -m pip \
    --no-input  `# Don't prompt for input` \
    --no-cache-dir  `# Don't use the cache` \
    --disable-pip-version-check  `# Don't check the PyPI for newer versions of Pip itself` \
    --require-virtualenv  `# Ensure we're running in the virtual environment` \
    install \
    --no-warn-script-location  `# Don't warn about bin/ not being on the PATH` \
    --no-index  `# Don't query the PyPI for anything` \
    --use-pep517  `# Force PEP 517 when building from source` \
    --find-links "$srcdir"/wheels  `# Pull dependencies from this vendored directory` \
    "$@"
}

do_pip --upgrade pip || exit $?
do_pip poetry.core || exit $?
do_pip \
  --force-reinstall  `# Always reinstall the tool if we make it here` \
  --editable  `# Ensure updates to the source propagate to the installation` \
  "$srcdir" || exit $?

{
  echo '#!/bin/sh'
  echo 'exec' "$1"/bin/hpctesttool '"$@"'
} > "$3"
chmod +x "$3"
