#!/bin/sh
# -*-Mode: sh;-*-

# $Id$

## **************************************************************************
##
## File: 
##    Regenerate 'configure' and 'Makefile.ins'
##
## Author:
##    Written by Nathan Tallent, Rice University.
##    
## **************************************************************************

autoreconf --force --install --verbose

#############################################################################
