#!/usr/bin/env python3

import click
from hpctoolkit.test.execution import hpcrun
from hpctoolkit.test.hardware import nvidia


@click.command()
@click.option("-p", "--procs", type=int, default=1, help="Expected number of processes")
@click.option(
    "-t", "--threads-per-proc", type=int, default=1, help="Expected number of threads per process"
)
@click.option("--trace", is_flag=True, help="Enable tracing (hpcrun -t)")
@click.option("--pc", is_flag=True, help="Enable PC sampling (hpcrun -e gpu=nvidia,pc")
@click.argument("cmd", nargs=-1, required=True)
def test_produces_profiles(
    procs: int, threads_per_proc: int, trace: bool, pc: bool, cmd: tuple[str]
):
    """Test that measuring CMD with CUDA support produces an expected number of profiles."""
    hw = nvidia()
    if pc:
        hw = nvidia(">=6.0")

    with hw, hpcrun(
        "-e", "gpu=nvidia" + (",pc" if pc else ""), ("-t" if trace else None), cmd=cmd
    ) as meas:
        meas.check_standard(
            procs=procs, threads_per_proc=threads_per_proc + (1 if trace else 0), traces=trace
        )


if __name__ == "__main__":
    test_produces_profiles()  # pylint: disable=no-value-for-parameter
